# Generated by Django 6.0.4 on 2026-04-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_created_2e2442_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_status_ecf387_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_categor_4138d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_author__f2f966_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
